#include "../../mk_int/src/base/mk_uint_base_char.c"
#include "../../mk_int/src/base/mk_uint_base_short.c"
#include "../../mk_int/src/base/mk_uint_base_int.c"
#include "../../mk_int/src/base/mk_uint_base_long.c"
#include "../../mk_int/src/base/mk_uint_base_llong.c"
#include "../../mk_int/src/base/mk_uint_base_128.c"

#include "../../mk_int/src/exact/mk_uint_8.c"
#include "../../mk_int/src/exact/mk_uint_16.c"
#include "../../mk_int/src/exact/mk_uint_32.c"
#include "../../mk_int/src/exact/mk_uint_64.c"
#include "../../mk_int/src/exact/mk_uint_128.c"
